//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        internal static string Connected_to {
            get {
                return ResourceManager.GetString("Connected_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from.
        /// </summary>
        internal static string Disconnected_from {
            get {
                return ResourceManager.GetString("Disconnected_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing plan.
        /// </summary>
        internal static string Executing_plan {
            get {
                return ResourceManager.GetString("Executing_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to.
        /// </summary>
        internal static string Failed_to_connect_to {
            get {
                return ResourceManager.GetString("Failed_to_connect_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        internal static string Failed_to_load {
            get {
                return ResourceManager.GetString("Failed_to_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read.
        /// </summary>
        internal static string Failed_to_read {
            get {
                return ResourceManager.GetString("Failed_to_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send.
        /// </summary>
        internal static string Failed_to_send {
            get {
                return ResourceManager.GetString("Failed_to_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send plan.
        /// </summary>
        internal static string Failed_to_send_plan {
            get {
                return ResourceManager.GetString("Failed_to_send_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file not found.
        /// </summary>
        internal static string file_not_found {
            get {
                return ResourceManager.GetString("file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loaded.
        /// </summary>
        internal static string loaded {
            get {
                return ResourceManager.GetString("loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Plan Data.
        /// </summary>
        internal static string Loading_PlanData {
            get {
                return ResourceManager.GetString("Loading_PlanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan.
        /// </summary>
        internal static string plan {
            get {
                return ResourceManager.GetString("plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan data.
        /// </summary>
        internal static string plan_data {
            get {
                return ResourceManager.GetString("plan_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan processed.
        /// </summary>
        internal static string Plan_processed {
            get {
                return ResourceManager.GetString("Plan_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan processing finished!.
        /// </summary>
        internal static string Plan_processing_finished_ {
            get {
                return ResourceManager.GetString("Plan_processing_finished_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan sent to server.
        /// </summary>
        internal static string Plan_sent_to_server {
            get {
                return ResourceManager.GetString("Plan_sent_to_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to port number.
        /// </summary>
        internal static string port_number {
            get {
                return ResourceManager.GetString("port_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        internal static string Progress_ {
            get {
                return ResourceManager.GetString("Progress_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending command to server.
        /// </summary>
        internal static string Sending_command_to_server {
            get {
                return ResourceManager.GetString("Sending_command_to_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending info to server.
        /// </summary>
        internal static string Sending_info_to_server {
            get {
                return ResourceManager.GetString("Sending_info_to_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending plan to server.
        /// </summary>
        internal static string Sending_plan_to_server {
            get {
                return ResourceManager.GetString("Sending_plan_to_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not connected.
        /// </summary>
        internal static string Server_is_not_connected {
            get {
                return ResourceManager.GetString("Server_is_not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not ready.
        /// </summary>
        internal static string Server_not_ready {
            get {
                return ResourceManager.GetString("Server_not_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to interrupt.
        /// </summary>
        internal static string to_interrupt {
            get {
                return ResourceManager.GetString("to_interrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong format data.
        /// </summary>
        internal static string wrong_format_data {
            get {
                return ResourceManager.GetString("wrong_format_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для распечатки плана облучения нажмите любую клавишу.
        /// </summary>
        internal static string Для_распечатки_плана_облучения_нажмите_любую_клавишу {
            get {
                return ResourceManager.GetString("Для_распечатки_плана_облучения_нажмите_любую_клавишу", resourceCulture);
            }
        }
    }
}
